accounts/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }

  authenticated(:user) { root 'dashboard#index', as: :authenticated_root }
  get :dashboard, to: 'dashboard#index'
  devise_scope(:user) { root to: 'sessions#new' }

  scope controller: 'logout' do
    get 'sign_out', to: 'logout#sign_out_page'
    post 'assign_logout_notice_back_url'
    get 'logout_notice'
    get 'timedout_user'
  end

  resources :passwords, only: %i[index create] do
    collection do
      get :reset
      post :reset, to: 'passwords#validate'
      get :email_sent
      get :invalid
      get :success
      get :edit
      patch :update
    end
  end

  scope module: 'organisations', path: '/' do
    get :create_account, to: 'organisations#create_account'
    post :create_account, to: 'organisations#submit_create_account'

    resources :organisations, only: %i[] do
      collection do
        get :how_many_vehicles
        post :how_many_vehicles, to: 'organisations#submit_how_many_vehicles'
        get :cannot_create
        get :sign_in_details
        post :sign_in_details, to: 'organisations#submit_sign_in_details'
        get :email_sent
        get :resend_email
        get :email_verified
        get :email_verification
        get :verification_failed
        get :verification_expired
      end
    end
  end

  scope module: 'vehicles_management', path: '/' do
    resources :fleets, only: %i[index], path: 'manage_vehicles' do
      collection do
        post :index, to: 'fleets#submit_search'
        get :vrn_not_found, to: 'fleets#vrn_not_found'
        get :choose_method
        post :choose_method, to: 'fleets#submit_choose_method'
        get :first_upload
        get :assign_remove
        get :remove
        post :remove, to: 'fleets#confirm_remove'
        get :export
      end
    end

    resources :vehicles, only: [] do
      collection do
        get :enter_details
        post :enter_details, to: 'vehicles#submit_details'
        get :details
        post :confirm_details
        get :exempt
        get :incorrect_details
        get :not_found
        post :confirm_not_found
        get :local_exemptions
        post :add_to_fleet
        post :confirm_and_add_exempt_vehicle_to_fleet
      end
    end

    resources :uploads, only: %i[index create] do
      collection do
        get :processing
        get :calculating_chargeability
        get :download_template
      end
    end
  end

  scope module: 'payments', path: '/' do
    resources :payments, only: :index do
      collection do
        post :local_authority
        scope '/which_days' do
          get :matrix
          post :matrix, to: 'payments#submit'
          get :vrn_not_found
          post :vrn_not_found, to: 'payments#submit_search'
        end
        get :no_chargeable_vehicles
        get :undetermined_vehicles
        get :clear_search
        get :review
        post :confirm_review
        get :review_details
        get :select_payment_method
        post :select_payment_method, to: 'payments#confirm_payment_method'
        get :initiate, to: 'credit_cards#initiate'
        get :result, to: 'credit_cards#result'
        get :in_progress
        get :success
        get :unsuccessful
        get :post_payment_details
        get :cancel, to: '/direct_debits/debits#cancel'
      end
    end
  end

  scope module: 'direct_debits', path: '/' do
    resources :debits, only: %i[index], path: 'direct_debits' do
      collection do
        get :set_up
        post :set_up, to: 'debits#submit_set_up'
        get :first_mandate
        get :confirm
        post :initiate
        get :success
        get :complete_setup
        get :unsuccessful
      end
    end
  end

  scope module: 'users_management', path: '/' do
    resources :users, controller: 'create_users', only: %i[new create] do
      collection do
        get :index, to: 'users#index'
        get :add_permissions
        post :add_permissions, to: 'create_users#confirm_permissions'
        get :confirmation
        get :set_up
        post :set_up, to: 'create_users#confirm_set_up'
        get :set_up_confirmation
      end

      member do
        get :edit, to: 'edit_users#edit'
        patch :update, to: 'edit_users#update'
        get :remove, to: 'remove_users#remove'
        post :remove, to: 'remove_users#confirm_remove'
      end
    end
  end

  scope module: 'account_details', path: '/' do
    get :edit_password, to: 'passwords#edit'
    patch :edit_password, to: 'passwords#update'

    get :primary_users_account_details, to: 'primary_users#primary_account_details'
    resources :primary_users, only: %i[] do
      collection do
        scope controller: 'organisation_names' do
          get :edit_name
          get :update_name
        end

        scope controller: 'emails' do
          get :edit_email
          post :update_email
          get :email_sent
          get :resend_email
          get :confirm_email
          get :validate_confirm_email
        end
      end
    end

    scope controller: 'account_cancellations' do
      get :account_closing_notice
      post :account_closing_notice, to: 'account_cancellations#confirm_account_closing_notice'
      get :account_cancellation
      post :account_cancellation, to: 'account_cancellations#submit_account_cancellation'
      get :account_closed
    end

    get :non_primary_users_account_details, to: 'non_primary_users#non_primary_account_details'
    resources :non_primary_users, only: %i[] do
      collection do
        scope controller: 'names' do
          get :edit_name
          get :update_name
        end
      end
    end
  end

  scope module: 'payment_history', path: '/', controller: 'payment_history' do
    get :payment_history
    get :payment_history_details
  end

  scope controller: 'static_pages' do
    get :accessibility_statement
    get :cookies
    get :help
    get :privacy_notice
    get :terms_and_conditions
  end

  scope controller: 'application' do
    get :build_id
    get :health
  end

  scope controller: 'errors' do
    get :not_found
    get :service_unavailable
  end

  scope controller: 'relevant_portal' do
    get :what_would_you_like_to_do
    post :what_would_you_like_to_do, to: 'relevant_portal#submit_what_would_you_like_to_do'
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#internal_server_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/503', to: 'errors#service_unavailable', via: :all
end

accounts/app/models/payment_history/company_payment.rb
# frozen_string_literal: true

##
# Module used for showing the payment history
module PaymentHistory
  ##
  # Represents the virtual model of the payment history, used in +app/views/payment_history/company_payment_history.html.haml+.
  #
  class CompanyPayment
    def initialize(data)
      @data = data.transform_keys { |key| key.underscore.to_sym }
    end

    # payment id
    def payment_id
      data[:payment_id]
    end

    # parsed payment date
    def date
      Date.parse(data[:payment_date]).strftime('%d/%m/%Y')
    end

    # payment made by
    def payer_name
      data[:payer_name]
    end

    # Clean Air Zone name
    def caz_name
      data[:caz_name]
    end

    # count of entries
    def entries_count
      data[:entries_count]
    end

    # amount paid
    def total_paid
      data[:total_paid]
    end

    private

    # Reader for data hash
    attr_accessor :data
  end
end

accounts/app/models/payment_history/details.rb
# frozen_string_literal: true

##
# Module used for showing the payment history
module PaymentHistory
  ##
  # Represents the virtual model of the detailed payment history
  #
  class Details
    include ::TimeZoneHelper
    # Initializer method.
    #
    # ==== Params
    # * +payment_id+ - Payment ID from backend DB
    #
    def initialize(payment_id)
      @payment_id = payment_id
    end

    # Returns a sorted by vrn PaymentHistory::DetailsPayment with payments associated with the account
    # and sort alphabetically by vrn
    def payments
      result = api_call['lineItems'].group_by { |key| key['vrn'] }
      result.map { |payment| PaymentHistory::DetailsPayment.new(vrn: payment.first, items: payment.second) }
            .sort_by(&:vrn)
    end

    # payment made by
    def payer_name
      api_call['payerName']
    end

    # date of payment, e.g.'Sunday 26 July 2020'
    def date
      Date.parse(api_call['paymentDate']).strftime('%A %d %B %Y')
    end

    # payment reference number
    def reference
      api_call['centralPaymentReference']
    end

    # provider payment id
    def provider_payment_id
      api_call['paymentProviderId']
    end

    # Returns an array of PaymentsHistory::PaymentModification model instances
    def payment_modifications
      group_by_dates = api_call['modificationHistory'].group_by do |e|
        parse_utc_date(e['modificationTimestamp']).in_time_zone.strftime('%A %d %B %Y')
      end
      group_by_types(group_by_dates)
    end

    private

    # Reader for Payment ID from backend DB
    attr_reader :payment_id

    # Calls the api go get all payment details
    def api_call
      @api_call ||= PaymentHistoryApi.payment_details(payment_id: payment_id)
    end

    # Group payment modification items by type and create
    # `PaymentsHistory::PaymentModification` instances
    def group_by_types(group_by_dates) # rubocop:disable Metrics/MethodLength
      group_by_dates.map do |day, modifications|
        {
          day =>
            {
              'refunds' => prepare_payment_modification(modifications.select do |e|
                e['entrantPaymentStatus'] == 'REFUNDED'
              end),
              'charges_back' => prepare_payment_modification(modifications.select do |e|
                e['entrantPaymentStatus'] == 'CHARGEBACK'
              end)
            }
        }
      end
    end

    # Prepare payment modifications items with proper data format and sort alphabetically by vrn
    def prepare_payment_modification(data)
      data.sort_by { |e| e['vrn'] }.map do |payment_modification|
        PaymentHistory::PaymentModification.new(payment_modification)
      end
    end
  end
end

accounts/app/models/payment_history/details_payment.rb
# frozen_string_literal: true

##
# Module used for showing the payment history details
module PaymentHistory
  ##
  # Represents the virtual model of the payment history, used in +app/views/payment_history/payment_history_details.html.haml+.
  #
  class DetailsPayment
    # Attributes accessor
    attr_accessor :vrn

    ##
    # Initializer method
    #
    # ==== Attributes
    #
    # * +vrn+ - vehicle registration number, eg. 'CU57ABC'
    # * +items+ - array of objects
    #   * +caseReference+ - unique traceability identifier
    #   * +chargePaid+ - amount paid, e.g. 4.23
    #   * +paymentStatus+ - status of payment, e.g. 'paid'
    #   * +travelDate+ - dates of entry, e.g. '2020-07-31'
    #
    def initialize(vrn:, items:)
      @vrn = vrn
      @items = items
    end

    # Parsed array of dates, e.g. ['Sunday 26 July 2020', 'Wednesday 29 July 2020']
    def dates
      items.map { |key| Date.parse(key['travelDate']) }.sort.map do |date|
        date.strftime('%A %d %B %Y')
      end
    end

    # sum of amount paid for all entries
    def total_paid
      items.map { |key| key['chargePaid'] }.sum
    end

    private

    # Reader for data hash
    attr_accessor :items
  end
end

accounts/app/models/payment_history/history.rb
# frozen_string_literal: true

##
# Module used for showing the payment history
module PaymentHistory
  ##
  # Represents the virtual model of the payment history
  #
  class History
    # Initializer method.
    #
    # ==== Params
    # * +account_id+ - Account ID from backend DB
    # * +user_id+ - Account User ID from backend DB
    # * +user_payments+ - boolean, to filter out company payments and show only users payments
    #
    def initialize(account_id, user_id, user_payments)
      @account_id = account_id
      @user_id = user_id
      @user_payments = user_payments
    end

    # Returns a PaymentHistory::PaginatedPayment with payments associated with the account
    # Includes data about page and total pages count
    def pagination(page:, per_page:)
      @pagination ||= begin
        data = PaymentHistoryApi.payments(
          account_id: account_id,
          user_id: user_id,
          user_payments: user_payments,
          page: page,
          per_page: per_page
        )
        PaymentHistory::PaginatedPayment.new(data)
      end
    end

    private

    # Attributes used internally
    attr_reader :account_id, :user_id, :user_payments
  end
end

accounts/app/models/payment_history/paginated_payment.rb
# frozen_string_literal: true

##
# Module used for showing the payment history
module PaymentHistory
  ##
  # Class used to display payment history
  #
  class PaginatedPayment
    # Take data returned from the PaymentHistoryApi.payments
    def initialize(data)
      @data = data
    end

    # Returns an array of PaymentHistory::Payment model instances
    def payments_list
      @payments_list ||= data['payments'].map { |payment| PaymentHistory::Payment.new(payment) }
    end

    # Returns current page value
    def page
      data['page'] + 1
    end

    # Returns the number of available pages
    def total_pages
      data['pageCount']
    end

    # Returns the total number of payments in the history
    def total_payments_count
      data['totalPaymentsCount']
    end

    # Returns the number of payments displayed per page
    def per_page
      data['perPage']
    end

    # Returns the index of the first payment on the page
    def range_start
      page * per_page - (per_page - 1)
    end

    # Returns the index of the last payment on the page
    def range_end
      max = page * per_page
      max > total_payments_count ? total_payments_count : max
    end

    # Determinate how many per page options should show
    def results_per_page
      case total_payments_count
      when 11..20
        [10, 20]
      when 21..30
        [10, 20, 30]
      when 31..40
        [10, 20, 30, 40]
      else
        [10, 20, 30, 40, 50]
      end
    end

    private

    # Attributes reader
    attr_reader :data
  end
end

accounts/app/controllers/payment_history/payment_history_controller.rb
# frozen_string_literal: true

##
# Module used for showing the payment history
module PaymentHistory
  ##
  # Controller used to show detailed information about the all company and users payments
  #
  class PaymentHistoryController < ApplicationController
    include CheckPermissions

    before_action -> { check_permissions(allow_view_details_history?) }, only: :payment_history_details

    ##
    # Renders the payment history page
    #
    # ==== Path
    #
    #    :GET /payment_history
    #
    def payment_history
      check_history_permissions
      @back_button_url = determinate_back_link_url
    rescue BaseApi::Error400Exception
      return redirect_to payment_history_path unless page_number == 1
    end

    ##
    # Renders the payment details page
    #
    # ==== Path
    #
    #    :GET /payment_history_details
    #
    def payment_history_details
      @details =  PaymentHistory::Details.new(payment_id)
      @payments = @details.payments
      @payment_modifications = @details.payment_modifications
      @back_button_url = determinate_back_link
    end

    private

    # Checks permissions and assigns paginated payment history
    def check_history_permissions
      if allow_view_payment_history?
        assign_paginated_history
      elsif allow_make_payments?
        assign_paginated_history(user_payments: true)
      else
        Rails.logger.warn('Access Denied. Redirects to :not_found page')
        redirect_to not_found_path
      end
    end

    # Assign paginated history to variable
    def assign_paginated_history(user_payments: false)
      @pagination = PaymentHistory::History.new(
        current_user.account_id, current_user.user_id, user_payments
      ).pagination(page: page_number, per_page: per_page)
    end

    # page number from params
    def page_number
      (params[:page] || 1).to_i
    end

    # per page size from params
    def per_page
      (params[:per_page] || 10).to_i
    end

    # payment_id from params
    def payment_id
      params['payment_id']
    end

    # Returns back link url, e.g '.../company_payment_history?page=3?back=true'
    def determinate_back_link_url
      PaymentHistory::BackLinkHistory.call(
        session: session,
        back_button: request.query_parameters['page']&.include?('back'),
        page: page_number,
        default_url: dashboard_url,
        url: payment_history_url
      )
    end

    # Returns back link url on the payment history details page
    # Assign +company_payment_history+ and +payment_details_back_link+ to the session
    def determinate_back_link
      session[:company_payment_history] = true if request.referer&.include?(payment_history_path)
      session[:payment_details_back_link] = request.referer || payment_history_path
    end
  end
end

accounts/app/views/payment_history/payment_history/_pagination.html.haml
- page = @pagination.page
- total_pages = @pagination.total_pages

%nav.moj-pagination#pagination-label
  %p.govuk-visually-hidden{'aria-labelledby': 'pagination-label'}
    Pagination navigation
  %ul.moj-pagination__list
    - unless page == 1
      = render 'payment_history/payment_history/pagination_button', button_text: 'Previous page', page: page - 1, form_class: 'prev'

    - (1..total_pages).each do |i|
      = render 'payment_history/payment_history/pagination_button', button_text: i, page: i, active: page == i

    - unless page == total_pages
      = render 'payment_history/payment_history/pagination_button', button_text: 'Next page', page: page + 1, form_class: 'next'

  - unless page > total_pages
    %p.moj-pagination__results
      Showing
      %b
        = @pagination.range_start
      to
      %b
        = @pagination.range_end
      of
      %b
        = @pagination.total_payments_count
      results

accounts/app/views/payment_history/payment_history/_pagination_button.html.haml
- active ||= false
- form_class ||= nil
- id = "pagination-button-#{transform_to_id(button_text)}"

- if active
  %li.moj-pagination__item.moj-pagination__item--active{id: id}
    = button_text
    - if button_text.is_a?(Integer)
      %span.govuk-visually-hidden
        page

- else
  %li.moj-pagination__item{id: id, class: ("moj-pagination__item--#{form_class}" if form_class)}
    = link_to(payment_history_path(page: page, per_page: params[:per_page]), class: 'moj-pagination__link') do
      = button_text
      - if button_text.is_a?(Integer)
        %span.govuk-visually-hidden
          page
      - if button_text.is_a?(String)
        %span.govuk-visually-hidden
          set of pages

accounts/app/views/payment_history/payment_history/_payment_modifications.html.haml
%p
  %strong
    Date received from Local Authority:
  = date

%div.scrollable-table
  %table.govuk-table
    %thead.govuk-table__head
      %tr.govuk-table__row
        %th.govuk-table__header.number-plate-header{scope: 'col'} Number plate
        %th.govuk-table__header.date-of-entry-header{scope: 'col'} Date of entry
        %th.govuk-table__header.charge-header{scope: 'col'} Charge
        %th.govuk-table__header.case-reference-header{scope: 'col'} Case reference
    %tbody.govuk-table__body
      - payment_modifications.each do |payment_modification|
        %tr.govuk-table__row
          %td.govuk-table__cell{scope: 'row'}
            = payment_modification.vrn
          %td.govuk-table__cell{scope: 'row'}
            = payment_modification.travel_date
          %td.govuk-table__cell{scope: 'row'}
            = parse_charge(payment_modification.amount)
          %td.govuk-table__cell{scope: 'row'}
            = payment_modification.reference

accounts/app/views/payment_history/payment_history/company_payment_history.html.haml
- title_and_header = "#{current_user.actual_account_name} payment history"
- content_for(:title, title_and_header)

= link_to 'Back', @back_button_url, class: 'govuk-back-link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-full
      %h1.govuk-heading-l
        = title_and_header

      - unless @pagination.payments_list.empty?
        %table.govuk-table
          %caption.govuk-table__caption
            %p View payments made by you and your team members.
          %thead.govuk-table__head
            %tr.govuk-table__row
              %th.govuk-table__header{scope: 'col'} Date of payment
              %th.govuk-table__header{scope: 'col'} Payment made by
              %th.govuk-table__header{scope: 'col'} Clean Air Zone
              %th.govuk-table__header{scope: 'col'} Entries paid for
              %th.govuk-table__header{scope: 'col'} Amount paid
              %th.govuk-table__header{scope: 'col'} Charge details
          %tbody.govuk-table__body
            - @pagination.payments_list.each_with_index do |payment, index|
              %tr.govuk-table__row
                %th.govuk-table__header{scope: 'row'}= payment.date
                %td.govuk-table__cell= payment.payer_name
                %td.govuk-table__cell= payment.caz_name
                %td.govuk-table__cell= payment.entries_count
                %td.govuk-table__cell= parse_charge(payment.total_paid)
                %td.govuk-table__cell
                  = link_to payment_history_details_path(payment_id: payment.payment_id), class: 'govuk-link', id: "payment-#{index}" do
                    View details

        = render 'payment_history/payment_history/company/pagination'

accounts/app/views/payment_history/payment_history/payment_history.html.haml
- title_and_header = "Payment history"
- content_for(:title, title_and_header)

= link_to 'Back', @back_button_url, class: 'govuk-back-link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-full
      %h1.govuk-heading-l
        = title_and_header

      - unless @pagination.payments_list.empty?
        %table.govuk-table
          %caption.govuk-table__caption
          - if allow_make_payments? && allow_view_payment_history?
            %p View payments made by you and your team members.
          - elsif allow_make_payments?
            %p View payments made by you.
          - else
            %p View payments made by your team members.

          %thead.govuk-table__head
            %tr.govuk-table__row
              %th.govuk-table__header{scope: 'col'} Date of payment
              %th.govuk-table__header{scope: 'col'} Payment made by
              %th.govuk-table__header{scope: 'col'} Clean Air Zone
              %th.govuk-table__header{scope: 'col'} Entries paid for
              %th.govuk-table__header{scope: 'col'} Total amount paid
              %th.govuk-table__header{scope: 'col'} Charge details
          %tbody.govuk-table__body
            - @pagination.payments_list.each_with_index do |payment, index|
              %tr.govuk-table__row
                %th.govuk-table__header{scope: 'row'}= payment.date
                %td.govuk-table__cell= payment.payer_name
                %td.govuk-table__cell= payment.caz_name
                %td.govuk-table__cell= payment.entries_count
                %td.govuk-table__cell
                  - if payment.refunded? || payment.charged_back?
                    Refund
                  - else
                    = parse_charge(payment.total_paid)
                %td.govuk-table__cell
                  = link_to payment_history_details_path(payment_id: payment.payment_id), class: 'govuk-link', id: "payment-#{index}" do
                    View details

        - if @pagination.total_payments_count > 10
          = render 'payment_history/payment_history/pagination'

          = form_tag(payment_history_path, method: :get) do
            .govuk-form-group
              %fieldset.govuk-fieldset{'aria-describedby': 'per_page'}
                %legend.govuk-visually-hidden Hide vehicles that are not charge in any Zone
                .govuk-checkboxes
                  .govuk-checkboxes__item
                    = select_tag('per_page',
                                 options_for_select(@pagination.results_per_page, params[:per_page]),
                                 class: 'govuk-select moj-pagination__results results-per-page-select',
                                 onchange: 'this.form.submit()')
                    = label_tag('per_page', 'Results per page', class: 'govuk-label moj-pagination__results results-per-page-select')

accounts/app/views/payment_history/payment_history/payment_history_details.html.haml
- title_and_header = 'Charge details'
- content_for(:title, title_and_header)

= link_to 'Back', @back_button_url, class: 'govuk-back-link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-full
      %h1.govuk-heading-l
        = title_and_header

      - if session[:company_payment_history]
        %p
          %strong Payment made by:
          = @details.payer_name
        %p
          %strong Date of payment:
          = @details.date
      %p
        %strong Payment reference:
        = @details.reference
      %p
        %strong Payment ID:
        = @details.provider_payment_id

      - unless @payments.empty?
        %table.govuk-table
          %caption.govuk-table__caption
            .govuk-visually-hidden Charge details table
          %thead.govuk-table__head
            %tr.govuk-table__row
              %th.govuk-table__header.number-plate-header{scope: 'col'} Number plate
              %th.govuk-table__header.date-of-entry-header{scope: 'col'} Dates of entry
              %th.govuk-table__header{scope: 'col', style: 'width: 35%'} Charge
          %tbody.govuk-table__body
            - @payments.each_with_index do |payment|
              %tr.govuk-table__row
                %td.govuk-table__cell= payment.vrn
                %td.govuk-table__cell
                  - payment.dates.each do |date|
                    = date
                    %br
                %td.govuk-table__cell= parse_charge(payment.total_paid)
                %td.govuk-table__cell
      - @payment_modifications.each do |payment_modification|
        - payment_modification.each do |date, type|
          - if type['refunds'].present?
            %h1.govuk-heading-m Refund
            = render 'payment_history/payment_history/payment_modifications', date: date, payment_modifications: type['refunds']

          - if type['charges_back'].present?
            %h1.govuk-heading-m Chargeback
            %p
              Payment returned after the charge was disputed.
            = render 'payment_history/payment_history/payment_modifications', date: date, payment_modifications: type['charges_back']

      %p
        = link_to 'Return to payment history', @back_button_url
      = render 'shared/print_link' if session[:company_payment_history]

accounts/app/views/payment_history/payment_history/user_payment_history.html.haml
- title_and_header = 'Your payment history'
- content_for(:title, title_and_header)

= link_to 'Back', @back_button_url, class: 'govuk-back-link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-full
      %h1.govuk-heading-l
        = title_and_header

      - unless @pagination.payments_list.empty?
        %table.govuk-table
          %caption.govuk-table__caption
            %p View payments made by you.
          %thead.govuk-table__head
            %tr.govuk-table__row
              %th.govuk-table__header{scope: 'col'} Date of payment
              %th.govuk-table__header{scope: 'col'} Clean Air Zone
              %th.govuk-table__header{scope: 'col'} Entries paid for
              %th.govuk-table__header{scope: 'col'} Amount paid
              %th.govuk-table__header{scope: 'col'} Charge details
          %tbody.govuk-table__body
            - @pagination.payments_list.each_with_index do |payment, index|
              %tr.govuk-table__row
                %th.govuk-table__header{scope: 'row'}= payment.date
                %td.govuk-table__cell= payment.caz_name
                %td.govuk-table__cell= payment.entries_count
                %td.govuk-table__cell= parse_charge(payment.total_paid)
                %td.govuk-table__cell
                  = link_to payment_history_details_path(payment_id: payment.payment_id), class: 'govuk-link', id: "payment-#{index}" do
                    View details

        = render 'payment_history/payment_history/user/pagination'