taxi-phv-data/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }

  authenticated(:user) { root 'upload#index', as: :authenticated_root }
  devise_scope(:user) { root to: 'devise/sessions#new' }

  resources :vehicles, only: %i[index] do
    collection do
      get :search
      post :search, to: 'vehicles#submit_search'
      get :historic_search
      get :not_found
    end
  end

  resources :upload, only: %i[] do
    collection do
      post :import
      get :processing
      get :success
      get :data_rules
    end
  end

  resources :passwords, only: %i[new create] do
    collection do
      get '/', to: redirect('/')
      get :success
      get :reset
      post :send_confirmation_code
      get :confirm_reset
      post :change
    end
  end

  scope controller: 'static_pages' do
    get :accessibility_statement
    get :cookies
    get :privacy_notice
  end

  scope controller: 'application' do
    get :build_id
    get :health
  end

  scope controller: 'errors' do
    get :service_unavailable
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#internal_server_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/503', to: 'errors#service_unavailable', via: :all
end

taxi-phv-data/app/controllers/upload_controller.rb
# frozen_string_literal: true

##
# Controller class for uploading a csv file.
#
class UploadController < ApplicationController
  # checks if a user is logged in
  before_action :authenticate_user!
  # checks if a user has a 'FORCE_NEW_PASSWORD' status
  before_action :redirect_to_new_password_path
  # checks if session +job+ is present
  before_action :check_job_data, only: %i[processing]
  # assign back button path
  before_action :assign_back_button_url, only: %i[data_rules]

  ##
  # Renders the upload page.
  #
  # ==== Path
  #
  #    :GET /upload/index
  #
  def index
    return unless session[:job]

    @job_errors = RegisterCheckerApi.job_errors(job_name, job_correlation_id)
    session[:job] = nil
  end

  ##
  # Upload csv file to AWS S3.
  #
  # ==== Path
  #
  #    :POST /upload/import
  #
  # ==== Params
  # * +file+ - uploaded file
  # * +current_user+ - an instance of the User class
  #
  def import
    CsvUploadService.call(file: file, user: current_user)
    correlation_id = SecureRandom.uuid
    job_name = RegisterCheckerApi.register_job(file.original_filename, correlation_id)
    session[:job] = {
      name: job_name,
      filename: file.original_filename,
      submission_time: submission_time,
      correlation_id: correlation_id
    }
    redirect_to processing_upload_index_path
  end

  ##
  # Checking of job status.
  #
  # ==== Path
  #
  #    :GET /upload/processing
  #
  # ==== Params
  # * +job_name+ - UUID, eg '98faf123-d201-48cb-8fd5-4b30c1f80918'
  # * +job_correlation_id+ - UUID, eg '98faf123-d201-48cb-8fd5-4b30c1f80918'
  #
  def processing
    result = RegisterCheckerApi.job_status(job_name, job_correlation_id)
    return if result == 'RUNNING'

    if result == 'SUCCESS'
      redirect_to success_upload_index_path
    else
      redirect_to authenticated_root_path, alert: 'Uploaded file is not valid'
    end
  end

  # Renders the data rules page.
  #
  # ==== Path
  #
  #    :GET /upload/data_rules
  #
  def data_rules
    # renders static page
  end

  ##
  # Renders page after successful CSV file processing.
  # Sends {SuccessEmail}[rdoc-ref:Ses::SendSuccessEmail] when visited first time after submission.
  #
  # ==== Path
  #    GET /upload/success
  #
  # ==== Attributes
  # * +job+ - hash in session
  #   * +name+ - UUID, job name received from backend API
  #   * +correlation_id+ - UUID, unique identifier used to communicate with backend API
  #   * +filename+ - string, name of the submitted file
  #   * +submission_time+ - string, time of the file submission in a proper format
  #
  def success
    return unless session[:job]

    unless Ses::SendSuccessEmail.call(user: current_user, job_data: job_data)
      @warning = I18n.t('upload.delivery_error')
    end
    session[:job] = nil
  end

  private

  # Returns a string.
  def job_name
    job_data[:name]
  end

  # Returns a string.
  def job_correlation_id
    job_data[:correlation_id]
  end

  # Returns a hash.
  def job_data
    session[:job].transform_keys(&:to_sym)
  end

  # Returns a string.
  def file
    params[:file]
  end

  # Checks if user +aws_status+ equality to 'FORCE_NEW_PASSWORD'.
  def redirect_to_new_password_path
    redirect_to new_password_path if current_user.aws_status == 'FORCE_NEW_PASSWORD'
  end

  # Checks if session +job+ is present.
  def check_job_data
    return unless session[:job].nil?

    Rails.logger.error 'Job identifier is missing'
    redirect_to root_path
  end

  # Returns current time in a proper format.
  def submission_time
    Time.current.strftime(Rails.configuration.x.time_format)
  end
end

taxi-phv-data/app/views/upload/data_rules.html.haml
- title_and_header = 'Taxi and PHV Data Portal'
- content_for(:title, title_and_header)

= link_to 'Back', @back_button_url, class: 'govuk-back-link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-xl
        = title_and_header

      %h2.govuk-heading-m File naming rules
      %p
        The file must be named according to the following format:
      %p
        CAZ-yyyy-mm-dd-XXXX.csv
      %p
        where:
        %ul.govuk-list-govuk-list--bullet
          %li
            %p yyyy-mm-dd represents the date the file was generated
          %li
            %p XXXX is the agreed identifier for your Licensing Authority
      %p
        For example, CAZ-2019-06-18-AuthorityID.csv
      %h2.govuk-heading-m Data rules
      %ul.govuk-list-govuk-list--bullet
        %li
          %p No header row is included
        %li
          %p No trailing row is included
        %li
          %p There is no trailing comma for the last field
        %li
          %p All characters comply with the 'accepted characters' below
        %li
          %p No field contains a newline character
        %li
          %p A field containing a comma or double quote must be quoted in double quotes ("...")
        %li
          %p
            Double quotes that form part of a field must be escaped with a double quote
            (i.e. a single " in a field becomes "") with the exception of values provided in the
            Taxi/PHV column
        %li
          %p No spaces should be used between field values and separating commas
        %li
          %p
            No padding should be applied to fields, unless leading or trailing space is a
            legitimate part of the field's value
        %li
          %p Each record is separated by a newline (ASCII carriage return)
        %li
          %p Optional fields with no values with be separated by a comma
        %li
          %p Start and End date format must be either ISO (YYYY-MM-DD) or DD/MM/YYYY
      %h2.govuk-heading-s
        Accepted characters
      %p Only the following characters may be included in the CSV file:
      %ul.govuk-list-govuk-list--bullet
        %li
          %p A to Z (upper case)
        %li
          %p a to z (lower case)

taxi-phv-data/app/views/upload/index.html.haml
%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      - if @job_errors
        = render 'upload/job_errors'
      - elsif alert
        = render 'shared/errors'
      %h1.govuk-heading-xl Taxi and PHV Data Portal
      %p
        Use this service to upload, manage and search data about taxis and PHVs in your licensing authority.
      %h2.govuk-heading-m Uploading your data
      %p
        Your data must be saved as a CSV file and be formatted according to the
        = succeed '.' do
          = link_to('data rules',  data_rules_upload_index_path)
        You should read the data rules before you upload a file to avoid errors.

      = form_tag(import_upload_index_path, multipart: true) do
        .govuk-form-group{class: ('govuk-form-group--error' if alert)}
          %label.govuk-label{for: "file-upload-1"}
            Upload a file
          - if alert
            %span#govuk-error-message.govuk-error-message
              %span.govuk-visually-hidden Error:
              = alert
          %input#file-upload-1.govuk-file-upload{class:('govuk-file-upload--error' if alert),
                                                 'aria-describedby': 'file-upload-1',
                                                 name: 'file',
                                                 type: 'file'}
        .govuk-form-group
          = submit_tag 'Upload', class: 'govuk-button', 'data-module': 'govuk-button'

taxi-phv-data/app/views/upload/processing.html.haml
= javascript_pack_tag 'autorefresh_page'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-l Validating submission...
      %p
        We are validating your CSV submission to National Taxi and PHV register.
        Please do not leave this page. It will automatically refresh to present your submission status.

      %p
        If the page does not refresh automatically in 30 seconds
        = succeed '.' do
          = link_to 'click here', processing_upload_index_path

taxi-phv-data/app/views/upload/success.html.haml
%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      .govuk-panel.govuk-panel--confirmation
        %h1.govuk-panel__title
          Upload successful
        .govuk-panel__body
          Taxi and PHV centralised database has been successfully updated
      - if @warning
        .govuk-warning-text
          %span.govuk-warning-text__icon{'aria-hidden' => true} !
          %strong.govuk-warning-text__text
            %span.govuk-warning-text__assistive Warning
            = @warning
      %h2.govuk-heading-m What happens next
      %p You can update your data whenever you need to by uploading a new file.
      %p
        = external_link_to('What did you think of this service?',
                           Rails.configuration.x.feedback_url,
                           id: 'feedback-survey-link')
        (takes 30 seconds).