payments/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'

  resources :vehicles, only: [] do
    collection do
      get :enter_details
      post :enter_details, to: 'vehicles#submit_details'
      get :details
      post :confirm_details
      get :uk_registered_details
      post :confirm_uk_registered_details
      get :incorrect_details
      get :unrecognised
      post :confirm_unrecognised
      get :compliant
      get :exempt
      get :not_determined
      post :not_determined, to: 'vehicles#submit_type'
    end
  end

  resources :non_dvla_vehicles, only: [:index] do
    collection do
      post :confirm_registration
      get :choose_type
      post :submit_type
    end
  end

  resources :charges, only: [] do
    collection do
      get :local_authority
      post :submit_local_authority
      get :review_payment
      get :discount_available
    end
  end

  resources :dates, only: [] do
    collection do
      get :select_period
      post :confirm_select_period

      get :daily_charge
      post :confirm_daily_charge

      get :weekly_charge
      post :confirm_weekly_charge

      get :select_daily_date
      post :confirm_daily_date

      get :select_weekly_date
      post :confirm_date_weekly
      get :select_second_weekly_date
      post :confirm_second_date_weekly

      get :select_weekly_period
      post :select_weekly_period, to: 'dates#confirm_select_weekly_period'
    end
  end

  resources :payments, only: %i[index create] do
    collection do
      get :success
      get :failure
    end
  end

  get :accessibility_statement, to: 'static_pages#accessibility_statement'
  get :cookies, to: 'static_pages#cookies'
  get :privacy_notice, to: 'static_pages#privacy_notice'

  get :build_id, to: 'application#build_id'
  get :health, to: 'application#health'

  get :service_unavailable, to: 'application#server_unavailable'
  match '/404', to: 'errors#not_found', via: :all
  # There is no 422 error page in design systems
  match '/422', to: 'errors#internal_server_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/503', to: 'errors#service_unavailable', via: :all
end

payments/app/controllers/dates_controller.rb
# frozen_string_literal: true

##
# Controls selecting dates.
#
class DatesController < ApplicationController # rubocop:disable Metrics/ClassLength
  # checks if VRN is present in the session
  before_action :check_vrn
  # checks if LA is present in the session
  before_action :check_compliance_details
  # checks if weekly taxi discount is possible for weekly paths
  before_action :check_weekly, only: %i[select_period confirm_select_period weekly_charge
                                        confirm_weekly_charge select_weekly_date select_second_weekly_date
                                        confirm_date_weekly confirm_second_date_weekly
                                        select_weekly_period confirm_select_weekly_period]
  # checks if weekly discount is possible to pay for today
  before_action :check_weekly_charge_today, only: %i[select_weekly_period confirm_select_weekly_period]
  # fetching +active_charge_start_date+ and assigns it to the variable
  before_action :assign_charge_start_date, only: %i[select_weekly_date select_second_weekly_date
                                                    confirm_date_weekly confirm_second_date_weekly]

  # resets which weeks was selected
  before_action :reset_week_selection, only: %i[select_weekly_date determinate_next_weekly_page]

  ##
  # Renders a select period page.
  #
  # ==== Path
  #    GET /dates/select_period
  #
  # ==== Validations
  # * +vrn+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +la_id+ - lack of LA redirects to {picking LA}[rdoc-ref:ChargesController.local_authority]
  #
  def select_period
    @return_path = case params['second_week']
                   when 'false'
                     select_weekly_date_dates_path
                   when 'true'
                     select_second_weekly_date_dates_path
                   else
                     local_authority_charges_path
                   end
  end

  ##
  # Validates if user selects at least one period.
  #
  # ==== Path
  #    POST /dates/confirm_select_period
  #
  # ==== Params
  # * +period+ - selected period
  #
  # ==== Validations
  # * +vrn+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +la_id+ - lack of LA redirects to {picking LA}[rdoc-ref:ChargesController.local_authority]
  # * +period+ - lack of the period redirects back to {select_period}[rdoc-ref:select_period]
  #
  def confirm_select_period
    if params[:period]
      SessionManipulation::SetChargePeriod.call(session: session, charge_period: params[:period])
      determinate_next_page
    else
      redirect_back_to(select_period_dates_path(id: transaction_id), true, :select_period)
    end
  end

  ##
  # Renders the charge value for a given LA and type of vehicle.
  #
  # ==== Path
  #    GET /dates/daily_charge
  #
  # ==== Validations
  # * +vrn+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +la_id+ - lack of LA redirects to {picking LA}[rdoc-ref:ChargesController.local_authority]
  #
  def daily_charge
    @undetermined_taxi = undetermined_taxi?
    @compliance_details = if @undetermined_taxi
                            UnrecognisedComplianceDetails.new(la_id: la_id)
                          else
                            ComplianceDetails.new(session[:vehicle_details])
                          end
    @return_path = determinate_return_path
  end

  ##
  # Validates if user confirmed being not exempt for a given LA.
  # If yes, redirects to the {next step}[rdoc-ref:select_daily_date]
  #
  # ==== Path
  #    POST /dates/confirm_daily_charge
  #
  # ==== Params
  # * +confirm-exempt+ - user confirmation of not being exempt, required in params
  #
  # ==== Validations
  # * +vrn+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +la_id+ - lack of LA redirects to {picking LA}[rdoc-ref:ChargesController.local_authority]
  # * +la_name+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +charge+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +confirm-exempt+ - lack of the confirmation redirects back to {daily charge}[rdoc-ref:ChargesController.daily_charge]
  #
  def confirm_daily_charge
    form = ConfirmationForm.new(params['confirm-exempt'])
    if form.valid?
      SessionManipulation::SetConfirmExempt.call(session: session)
      redirect_to select_daily_date_dates_path(id: transaction_id)
    else
      alert = I18n.t('confirmation_form.exemption')
      redirect_back_to(daily_charge_dates_path(id: transaction_id), alert, :daily_charge)
    end
  end

  ##
  # Renders the list of dates to pick. Already paid dates are marked as disabled.
  #
  # ==== Path
  #    GET /dates/select_daily_date
  #
  # ==== Validations
  # * +vrn+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +la_id+ - lack of LA redirects to {picking LA}[rdoc-ref:ChargesController.local_authority]
  # * +la_name+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +charge+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  #
  def select_daily_date
    @charge_start_date = FetchSingleCazData.call(zone_id: la_id)&.active_charge_start_date
    service = Dates::Daily.new(vrn: vrn, zone_id: la_id, charge_start_date: @charge_start_date)
    @dates = service.chargeable_dates
    @d_day_notice = service.d_day_notice
    @all_paid = @dates.all? { |date| date[:disabled] }
  end

  ##
  # Validates if user selects at least one date and the dates were not paid before.
  #
  # ==== Path
  #    POST /dates/confirm_daily_date
  #
  # ==== Params
  # * +dates+ - selected dates
  #
  # ==== Validations
  # * +vrn+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +la_id+ - lack of LA redirects to {picking LA}[rdoc-ref:ChargesController.local_authority]
  # * +la_name+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +charge+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +dates+ - lack of the date redirects back to {daily charge}[rdoc-ref:select_daily_date]
  #
  def confirm_daily_date
    dates = params[:dates]
    if dates && check_already_paid(dates)
      SessionManipulation::CalculateTotalCharge.call(session: session, dates: dates)
      redirect_to review_payment_charges_path(id: transaction_id)
    else
      alert = I18n.t(dates ? 'paid' : 'empty', scope: 'dates.daily')
      redirect_back_to(select_daily_date_dates_path(id: transaction_id), alert, :dates)
    end
  end

  ##
  # Renders the weekly charge value for a given LA and type of vehicle.
  #
  # ==== Path
  #    GET /dates/weekly_charge
  #
  # ==== Validations
  # * +vrn+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +la_id+ - lack of LA redirects to {picking LA}[rdoc-ref:ChargesController.local_authority]
  #
  def weekly_charge
    Dates::AssignBackButtonDate.call(session: session)
    @compliance_details = ComplianceDetails.new(session[:vehicle_details])
    @weekly_charge = 50.00
    @return_path = determinate_return_path
  end

  ##
  # Validates if user confirmed being not exempt for a given LA.
  # If yes, redirects to the {next step}[rdoc-ref:select_daily_date]
  #
  # ==== Path
  #    POST /dates/confirm_daily_charge
  #
  # ==== Params
  # * +confirm-exempt+ - user confirmation of not being exempt, required in params
  #
  # ==== Validations
  # * +vrn+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +la_id+ - lack of LA redirects to {picking LA}[rdoc-ref:ChargesController.local_authority]
  # * +la_name+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +charge+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +confirm-exempt+ - lack of the confirmation redirects back to {daily charge}[rdoc-ref:daily_charge]
  #
  def confirm_weekly_charge
    form = ConfirmationForm.new(params['confirm-exempt'])
    if form.confirmed?
      SessionManipulation::SetConfirmExempt.call(session: session)
      redirect_to select_weekly_date_dates_path(id: transaction_id)
    else
      alert = I18n.t('confirmation_form.exemption')
      redirect_back_to(weekly_charge_dates_path(id: transaction_id), alert, :weekly_charge)
    end
  end

  ##
  # Renders the list of weekly dates to pick.
  #
  # ==== Path
  #    GET /dates/select_weekly_date
  #
  # ==== Validations
  # * +vrn+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +la_id+ - lack of LA redirects to {picking LA}[rdoc-ref:ChargesController.local_authority]
  # * +la_name+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +charge+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  #
  def select_weekly_date
    handle_back_action(second_week_selected: false,
                       session_date: week_start_days.first,
                       back_button_date: back_button_week_dates.first)

    SessionManipulation::SetSelectedWeek.call(session: session)
    @return_path = select_weekly_date_return_path
    handle_select_weekly_date
  end

  ##
  # Renders the list of weekly dates to pick as a second week.
  #
  # ==== Path
  #    GET /dates/select_second_weekly_date
  #
  # ==== Validations
  # * +vrn+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]
  # * +la_id+ - lack of LA redirects to {picking LA}[rdoc-ref:ChargesController.local_authority]
  # * +la_name+ - lack of VRN redirects to {enter_details}[rdoc-ref:VehiclesController.enter_details]

payments/app/helpers/dates_helper.rb
# frozen_string_literal: true

##
# Helper module for DatesController
module DatesHelper
  # Checks if the date was already selected by the user.
  # Returns boolean.
  def checked_daily?(value)
    session.dig(:vehicle_details, 'dates')&.include?(value)
  end

  # Checks if the date is the beginning of the previously selected period.
  # Returns boolean.
  def checked_weekly?(value)
    value == session.dig(:vehicle_details, 'dates')&.first
  end

  # Checks if vehicle details are undetermined
  # Returns boolean.
  def undetermined_vehicle?
    session.dig(:vehicle_details, 'undetermined').present?
  end

  # Returns the date's name with today and paid marks
  def display_date(date)
    value = today_not_paid(date) ? tag.b(date[:name]) : date[:name]
    value += ' (Today)' if date[:today]
    value += ' - Paid' if date[:disabled]
    value
  end

  # Returns today hint, e.g. 'Your weekly charge will expire on Tue 09 June 2020'
  # Renders on app/views/dates/select_weekly_period.html.haml view
  def today_hint
    end_date = (Date.current + 6.days).strftime('%a %d %B %Y')
    "Your weekly charge will expire on #{end_date}"
  end

  # Lists disabled dates for selected week start date
  # Disables 6 days before (to prevent payment overlapping) and 6 days after week_start_date
  # Returns array of dates in string YYYY-MM-DD format
  def disable_week(week_start_date)
    selected_date = Date.strptime(week_start_date, Dates::Base::VALUE_DATE_FORMAT)
    (selected_date - 6.days)
      .upto(selected_date + 6.days)
      .map { |date| date.strftime(Dates::Base::VALUE_DATE_FORMAT) }
  end

  private

  # Checks if today day is not paid
  def today_not_paid(date)
    date[:today] & !date[:disabled]
  end
end

payments/app/views/dates/select_weekly_date/_content.html.haml
#dates_data{data: @dates.to_json}
#d-day_data{data: @charge_start_date}

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      - if alert
        = render 'common/error_summary',
          error_msg_div: '#select-weekly-date-error',
          error_msg: alert

      %h1.govuk-heading-l
        = title_and_header
      %p A weekly charge allows you to drive in future clean air zones for 7 consecutive days.
      %p A daily charge period runs from midnight to midnight.

      - if @all_paid
        .govuk-inset-text
          If the weekly charge you want to pay for is not available,
          it is because you have paid for a date in those 7 consecutive days.

      - if @d_day_notice
        .govuk-inset-text
          The Clean Air Zone charge came into operation on #{parse_single_date(@charge_start_date)}.

      = form_tag submit_url, method: :post do
        .govuk-form-group{class: ('govuk-form-group--error' if alert)}
          %fieldset.govuk-fieldset
            %h2.govuk-heading-m
              Start date
            %span.govuk-hint
              For example, 12 11 2020
            - if alert
              %span#select-weekly-date-error.govuk-error-message
                %span.govuk-visually-hidden Error:
                = alert
            = render 'dates/select_weekly_date/input_normal', input_date: @input_date

        %p#week-last-day-notice

        %details.govuk-details{'data-module': 'govuk-details'}
          %summary.govuk-details__summary
            %span.govuk-details__summary-text
              Why can’t I select certain dates?
          .govuk-details__text
            %p If you can't select the date you want to pay for, it may be because:
            %ul
              %li
                You have paid a charge for that date
              %li
                You have paid for part of those consecutive 7 days
              %li
                It is outside the 13 days you can pay a charge for
            %p If the date you want to pay for is more than 7 days ago you may be sent a Penalty Charge Notice (PCN)

        = submit_tag 'Continue', class: 'govuk-button', 'data-module': 'govuk-button' if !@all_paid

      = javascript_pack_tag 'datePicker'

      %p= link_to 'Pay for 1 day instead', select_period_dates_path(second_week: second_week), id: 'pay_instead'

      - if second_week
        %p= link_to 'Cancel adding a second week', review_payment_charges_path(cancel_second_week: true), id: 'cancel_second_week'

payments/app/views/dates/select_weekly_date/_input_normal.html.haml
.govuk-date-input
  .govuk-date-input__item
    %label.govuk-label.govuk-date-input__label
      Day
    %input.govuk-input.govuk-date-input__input.govuk-input--width-2#date-day{type: 'text',
                                                                             class: ('govuk-input--error' if alert),
                                                                             name: 'date_day',
                                                                             value: (@input_date.day if @input_date),
                                                                             pattern: '^[0-9]{1,2}$',
                                                                             inputmode: 'numeric'}
  .govuk-date-input__item
    %label.govuk-label.govuk-date-input__label
      Month
    %input.govuk-input.govuk-date-input__input.govuk-input--width-2#date-month{type: 'text',
                                                                               class: ('govuk-input--error' if alert),
                                                                               name: 'date_month',
                                                                               value: (@input_date.month if @input_date),
                                                                               pattern: '^[0-9]{1,2}$',
                                                                               inputmode: 'numeric'}
  .govuk-date-input__item
    %label.govuk-label.govuk-date-input__label
      Year
    %input.govuk-input.govuk-date-input__input.govuk-input--width-4#date-year{type: 'text',
                                                                              class: ('govuk-input--error' if alert),
                                                                              name: 'date_year',
                                                                              value: (@input_date.year if @input_date),
                                                                              pattern: '^[0-9]{4}$',
                                                                              inputmode: 'numeric'}
  .govuk-date-input__item.litepicker-input-container
    %label.sm-visually-hidden
      Date picker for start date
    %i#litepicker.far.fa-calendar-alt