accounts/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }

  authenticated(:user) { root 'dashboard#index', as: :authenticated_root }
  get :dashboard, to: 'dashboard#index'
  devise_scope(:user) { root to: 'sessions#new' }

  scope controller: 'logout' do
    get 'sign_out', to: 'logout#sign_out_page'
    post 'assign_logout_notice_back_url'
    get 'logout_notice'
    get 'timedout_user'
  end

  resources :passwords, only: %i[index create] do
    collection do
      get :reset
      post :reset, to: 'passwords#validate'
      get :email_sent
      get :invalid
      get :success
      get :edit
      patch :update
    end
  end

  scope module: 'organisations', path: '/' do
    get :create_account, to: 'organisations#create_account'
    post :create_account, to: 'organisations#submit_create_account'

    resources :organisations, only: %i[] do
      collection do
        get :how_many_vehicles
        post :how_many_vehicles, to: 'organisations#submit_how_many_vehicles'
        get :cannot_create
        get :sign_in_details
        post :sign_in_details, to: 'organisations#submit_sign_in_details'
        get :email_sent
        get :resend_email
        get :email_verified
        get :email_verification
        get :verification_failed
        get :verification_expired
      end
    end
  end

  scope module: 'vehicles_management', path: '/' do
    resources :fleets, only: %i[index], path: 'manage_vehicles' do
      collection do
        post :index, to: 'fleets#submit_search'
        get :vrn_not_found, to: 'fleets#vrn_not_found'
        get :choose_method
        post :choose_method, to: 'fleets#submit_choose_method'
        get :first_upload
        get :assign_remove
        get :remove
        post :remove, to: 'fleets#confirm_remove'
        get :export
      end
    end

    resources :vehicles, only: [] do
      collection do
        get :enter_details
        post :enter_details, to: 'vehicles#submit_details'
        get :details
        post :confirm_details
        get :exempt
        get :incorrect_details
        get :not_found
        post :confirm_not_found
        get :local_exemptions
        post :add_to_fleet
        post :confirm_and_add_exempt_vehicle_to_fleet
      end
    end

    resources :uploads, only: %i[index create] do
      collection do
        get :processing
        get :calculating_chargeability
        get :download_template
      end
    end
  end

  scope module: 'payments', path: '/' do
    resources :payments, only: :index do
      collection do
        post :local_authority
        scope '/which_days' do
          get :matrix
          post :matrix, to: 'payments#submit'
          get :vrn_not_found
          post :vrn_not_found, to: 'payments#submit_search'
        end
        get :no_chargeable_vehicles
        get :undetermined_vehicles
        get :clear_search
        get :review
        post :confirm_review
        get :review_details
        get :select_payment_method
        post :select_payment_method, to: 'payments#confirm_payment_method'
        get :initiate, to: 'credit_cards#initiate'
        get :result, to: 'credit_cards#result'
        get :in_progress
        get :success
        get :unsuccessful
        get :post_payment_details
        get :cancel, to: '/direct_debits/debits#cancel'
      end
    end
  end

  scope module: 'direct_debits', path: '/' do
    resources :debits, only: %i[index], path: 'direct_debits' do
      collection do
        get :set_up
        post :set_up, to: 'debits#submit_set_up'
        get :first_mandate
        get :confirm
        post :initiate
        get :success
        get :complete_setup
        get :unsuccessful
      end
    end
  end

  scope module: 'users_management', path: '/' do
    resources :users, controller: 'create_users', only: %i[new create] do
      collection do
        get :index, to: 'users#index'
        get :add_permissions
        post :add_permissions, to: 'create_users#confirm_permissions'
        get :confirmation
        get :set_up
        post :set_up, to: 'create_users#confirm_set_up'
        get :set_up_confirmation
      end

      member do
        get :edit, to: 'edit_users#edit'
        patch :update, to: 'edit_users#update'
        get :remove, to: 'remove_users#remove'
        post :remove, to: 'remove_users#confirm_remove'
      end
    end
  end

  scope module: 'account_details', path: '/' do
    get :edit_password, to: 'passwords#edit'
    patch :edit_password, to: 'passwords#update'

    get :primary_users_account_details, to: 'primary_users#primary_account_details'
    resources :primary_users, only: %i[] do
      collection do
        scope controller: 'organisation_names' do
          get :edit_name
          get :update_name
        end

        scope controller: 'emails' do
          get :edit_email
          post :update_email
          get :email_sent
          get :resend_email
          get :confirm_email
          get :validate_confirm_email
        end
      end
    end

    scope controller: 'account_cancellations' do
      get :account_closing_notice
      post :account_closing_notice, to: 'account_cancellations#confirm_account_closing_notice'
      get :account_cancellation
      post :account_cancellation, to: 'account_cancellations#submit_account_cancellation'
      get :account_closed
    end

    get :non_primary_users_account_details, to: 'non_primary_users#non_primary_account_details'
    resources :non_primary_users, only: %i[] do
      collection do
        scope controller: 'names' do
          get :edit_name
          get :update_name
        end
      end
    end
  end

  scope module: 'payment_history', path: '/', controller: 'payment_history' do
    get :payment_history
    get :payment_history_details
  end

  scope controller: 'static_pages' do
    get :accessibility_statement
    get :cookies
    get :help
    get :privacy_notice
    get :terms_and_conditions
  end

  scope controller: 'application' do
    get :build_id
    get :health
  end

  scope controller: 'errors' do
    get :not_found
    get :service_unavailable
  end

  scope controller: 'relevant_portal' do
    get :what_would_you_like_to_do
    post :what_would_you_like_to_do, to: 'relevant_portal#submit_what_would_you_like_to_do'
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#internal_server_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/503', to: 'errors#service_unavailable', via: :all
end

accounts/app/controllers/dashboard_controller.rb
# frozen_string_literal: true

##
# Controller class for the home page
#
class DashboardController < ApplicationController
  include CheckPermissions
  include CazLock
  include PaymentFeatures

  before_action :set_cache_headers, only: %i[index]
  before_action :clear_input_history, only: :index

  # Handle Bath D-Day notice
  before_action :assign_payment_enabled, only: :index
  before_action :assign_bath_d_day_date, only: :index

  ##
  # Renders the dashboard page.
  #
  # ==== Path
  #
  #    :GET /dashboard
  #
  def index
    @vehicles_count = current_user.fleet.total_vehicles_count
    @any_dd_cazes_enabled = any_dd_cazes_enabled
    @mandates_present = check_mandates
    account_users = load_account_users
    @users_present = check_users(account_users)
    @multi_payer_account = account_users.multi_payer_account?
    @days_count = days_to_password_expiry
    @payments_present = check_payments
  end

  private

  # Do not perform api call if user is not in a beta group or direct debits disabled or user don't have permission
  def check_mandates
    return false unless allow_manage_mandates?

    if current_user&.beta_tester || Rails.configuration.x.feature_direct_debits.to_s.downcase == 'true'
      DirectDebits::Debit.new(current_user.account_id).active_mandates.any?
    else
      false
    end
  end

  # Calls api to check if at least one direct debit caz is enabled for non beta testers
  def any_dd_cazes_enabled
    return true if current_user&.beta_tester

    Rails.logger.info "[#{self.class.name}] Getting enabled direct debit clean air zones"
    DebitsApi.mandates(account_id: current_user.account_id).any? { |caz| caz['directDebitEnabled'] == true }
  end

  # Loads account users
  def load_account_users
    UsersManagement::AccountUsers.new(account_id: current_user.account_id, user_id: current_user.user_id)
  end

  # Do not perform api call if user don't have permission
  def check_users(account_users)
    return false unless allow_manage_users?

    account_users.filtered_users.any?
  end

  # Do not perform api call if user don't have permission
  def check_payments
    if allow_view_payment_history?
      check_payments_present
    elsif allow_make_payments?
      check_payments_present(user_payments: true)
    else
      false
    end
  end

  # Checks if payments assigned to account or user are present.
  def check_payments_present(user_payments: false)
    PaymentHistory::History.new(current_user.account_id, current_user.user_id, user_payments)
                           .pagination(page: 0, per_page: 1)
                           .total_payments_count.positive?
  end

  # clear user flow history from the session
  def clear_input_history
    clear_manage_vehicles_history
    clear_make_payment_history
    clear_manage_users_history
    clear_payment_history
  end

  # clear manage vehicles inputs
  def clear_manage_vehicles_history
    session[:choose_method] = nil
  end

  # clear manage users inputs
  def clear_manage_users_history
    session[:new_user] = nil
  end

  # clear payments history back links
  def clear_payment_history
    session[:back_link_history] = nil
  end
end

accounts/app/views/dashboard/_company_payment_history.html.haml
%article.dashboard-total-group.govuk-grid-column-one-third
  %p.govuk-body{class: 'govuk-!-font-size-16 govuk-!-margin-top-9'}
    %strong
      = link_to("#{current_user.actual_account_name} payment history" , company_payment_history_path, id: 'company-payment-history')
  %p.govuk-body View payments made by your team members.

accounts/app/views/dashboard/_d_day_notice.html.haml
- formatted_date = @bath_d_day_date&.strftime('%e %B')

.govuk-grid-row
  .govuk-grid-column-full
    = render 'shared/warning' do
      = "We will add new features when charging starts on #{formatted_date} allowing you to pay to drive in Bath."

accounts/app/views/dashboard/_direct_debit.html.haml
%article.dashboard-total-group.govuk-grid-column-one-third
  - if @mandates_present
    %p.govuk-body{class: 'govuk-!-font-size-16 govuk-!-margin-top-9'}
      %strong
        = link_to('Pay by bank account', debits_path, id: 'direct-debit')
    %p.govuk-body View the agreements you’ve previously set up.
  - else
    %p.govuk-body{class: 'govuk-!-font-size-16 govuk-!-margin-top-9'}
      %strong
        = link_to('Pay by bank account', debits_path, id: 'direct-debit')
    %p.govuk-body
      Use your bank details to pay a charge as an alternative to paying by card.

accounts/app/views/dashboard/_help.html.haml
%article.dashboard-total-group.govuk-grid-column-one-third
  %p.govuk-body{class: 'govuk-!-font-size-16 govuk-!-margin-top-9'}
    %strong
      = link_to('Help', help_path, id: 'help')
  %p.govuk-body View maps, see when the zones are live, find out about exemptions and contact us.

accounts/app/views/dashboard/_make_payment.html.haml
%article.dashboard-total-group.govuk-grid-column-one-third
  %p.govuk-body{class: 'govuk-!-font-size-16 govuk-!-margin-top-9'}
    %strong
      = link_to('Make a payment', payments_path, id: 'payment')
  %p.govuk-body
    = succeed '.' do
      Pay your vehicle charges by credit/debit card
      - if direct_debits_enabled?
        or bank account (you must set this up before paying this way)

accounts/app/views/dashboard/_manage_users.html.haml
%article.dashboard-total-group.govuk-grid-column-one-third

  - if @users_present
    %p.govuk-body{class: 'govuk-!-font-size-16 govuk-!-margin-top-9'}
      %strong
        = link_to('Manage users', users_path, id: 'manage-users')
    %p.govuk-body Add and remove users or change their permissions.

  - else
    %p.govuk-body{class: 'govuk-!-font-size-16 govuk-!-margin-top-9'}
      %strong
        = link_to('Add a user', new_user_path, id: 'add-user')
    %p.govuk-body Add team members to help manage your account.

accounts/app/views/dashboard/_manage_vehicles.html.haml
%article.dashboard-total-group.govuk-grid-column-one-third
  %p.govuk-body{class: 'govuk-!-font-size-16 govuk-!-margin-top-9'}
    %strong
      = link_to('Manage vehicles and view charges', fleets_path, id: 'manage-vehicles')
  %p.govuk-body Upload your number plates via spreadsheet or one-by-one.

accounts/app/views/dashboard/_payment_history.html.haml
%article.dashboard-total-group.govuk-grid-column-one-third
  %p.govuk-body{class: 'govuk-!-font-size-16 govuk-!-margin-top-9'}
    %strong
      = link_to('Payment history' , payment_history_path, id: 'payment-history')
  %p.govuk-body
    = link_description

accounts/app/views/dashboard/_update_password_notice.html.haml
- days_text = @days_count == 1 ? '1 day' : "#{@days_count} days"

= render 'shared/warning' do
  = "Your password will expire in #{days_text}."
  = link_to 'Update it now', edit_passwords_path

accounts/app/views/dashboard/_user_payment_history.html.haml
%article.dashboard-total-group.govuk-grid-column-one-third
  %p.govuk-body{class: 'govuk-!-font-size-16 govuk-!-margin-top-9'}
    %strong
      = link_to('Your payment history', user_payment_history_path, id: 'user-payment-history')
  %p.govuk-body View payments made by you.

accounts/app/views/dashboard/index.html.haml
- title_and_header = raw("#{current_user.actual_account_name} account home")
- content_for(:title, title_and_header)
- disable_payment_features = !@payment_features_enabled && (allow_make_payments? || allow_view_payment_history?)
%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds

      = render 'shared/banners'

      %h1.govuk-heading-l= title_and_header

      = render 'update_password_notice' if @days_count && @days_count <= 10

      %p
        This service works by you telling us the number of days your vehicles drive in a Clean Air Zone.
        The number plates determine if the vehicles meet emissions standards in a zone.
        If they don't, you can see what the charges are and pay them.
      - if @vehicles_count == 0
        .govuk-inset-text
          You need to upload all your number plates before making a payment.
      - elsif @vehicles_count == 1
        .govuk-inset-text
          You need to add at least one more vehicle before making a payment.

  = render 'd_day_notice' if disable_payment_features

  .govuk-grid-row
    = render 'manage_vehicles' if allow_manage_vehicles?
    = render 'direct_debit' if direct_debits_enabled? && allow_manage_mandates? && @any_dd_cazes_enabled
    = render 'manage_users' if allow_manage_users?
    - if !disable_payment_features
      = render 'make_payment' if allow_make_payments? && @vehicles_count >= 2
      - if allow_make_payments? && allow_view_payment_history?
        - link_description = 'View payments made by you and your team members.'
      - elsif allow_make_payments?
        - link_description = 'View payments made by you.'
      - elsif allow_view_payment_history?
        - link_description = 'View payments made by your team members.'
      = render 'payment_history', link_description: link_description if link_description && @payments_present

    = render 'help'